### ISSUE TITLE
Removing Any breaks backward compatibility

### ISSUE THREAD

**Issue by lann** [mndrix/ps#2]
c047077 removed the exported Any type alias, breaking code that references it.

**Comment by mndrix** [comment]
Thanks for catching that @lann I removed the type during development so the type checker could help me find all the places that depended on it.  I meant to restore it after the refactoring.  Sorry.

I'll push a fix shortly along with an explicit deprecation message in the documentation.

**Comment by lann** [comment]
There is still a backward incompatibility stemming from the ForEach method signature. Go does not treat `func(string, Any)` and `func(string, interface{})` as compatible signatures.

**Comment by mndrix** [comment]
Thanks for pointing that out.

I've changed my mind on supporting backward compatibility in this way.  See commit 35fef6f28be7e47a87d8a71ef5b80cbf2c4c167a for my reasoning and work arounds for those impacted.
