### ISSUE TITLE
Immutable js

### ISSUE THREAD

**Issue by ghost** [mndrix/ps#7]
Does this allow writting immutable code ?

I ask because I am porting some J's code to holang and the J's codes only dependency is immutable js library made by Facebook.

The code I am porting

https://github.com/automerge/automerge/tree/master/src

The Facebook lib.

https://facebook.github.io/immutable-js/

**Comment by mndrix** [comment]
Yes. This package is similar to immutable.js. We don't provide as many data structures as they do, but we invite pull requests adding more. Good luck on your project.
